removed unnecessary error message
removed necessary error message: 3 error messages are displayed when the user passes an option mrai doesn't recognize. One has been removed.

diff --git a/mrai b/mrai
--- a/mrai
+++ b/mrai
@@ -1011,7 +1011,9 @@ while getopts 'uSircl' flag; do
 			fi;;
 		l) LIST=1;;
 		#all else
-		*) echo -e "\nError: Option not recognized.\n\n$h\n"
+		*)
+			echo -e "\nError: Option not recognized.\n\n$h\n"
+			exit 2;;
 	esac
 done
 #start:
