Update mrai
Added support for installation of Flatpaks from Remotes other than Flathub.

diff --git a/mrai b/mrai
--- a/mrai
+++ b/mrai
@@ -73,7 +73,11 @@ flatinstall () {
 				set -- "$r"
 				test="$2"
 				if [ -z "$test" ]; then		
-					flatpak install -y flathub "$r"
+					list=$(flatpak remotes)
+					list1=$(echo "$list" | awk '{print $1}')
+					for entry in $list1; do
+						flatpak install -y "$entry" "$r" && break || echo -e "\nFlatpak installation from $entry failed.\n"
+					done
 					loop="0"
 				else
 					echo -e "\nERROR: Multiple Installation Candidates Detected.\n"
