Update mrai
fixed gitautoinstall and gitmaninstall error when trying all install methods, changed install sequence from: apt, snap, githubauto, flatpak, githubman;    to : apt, snap, flatpak, githubauto, githubman

diff --git a/mrai b/mrai
--- a/mrai
+++ b/mrai
@@ -381,8 +381,7 @@ else
 		else
 			echo -e "\nAttempting to install\n"
 			pass="$y"	
-			aptinstall || snapinstall || gitautoinst || flatinstall || gitmaninstall || echo -e "\nWe're sorry. All installation methods failed.\nPlease make sure that you have the Github username,\nrepo name, and package name spelled correctly\n" && exit 2
-		fi
+			aptinstall || snapinstall || flatinstall || pass=$z && gitautoinst || gitmaninstall || echo -e "\nWe're sorry. All installation methods failed.\nPlease make sure that you have the Github username,\nrepo name, and package name spelled correctly\n" && exit 2		fi
 	elif [ "$x" == "-r" ] || [ "$x" == "--remove" ] || [ "$x" == "--uninstall" ]; then
 		pass="$y"		
 		checkinstalltype
