Changed mrai flag detection system

diff --git a/mrai b/mrai
--- a/mrai
+++ b/mrai
@@ -26,11 +26,11 @@ if [[ "$EUID" == "0" ]]; then
     echo -e "\nPlease do not run mrai with root privleges. This will cause file system issues with GitHub installations.\n" && exit 2
 fi
 #pre-config
-version="0.6.2-alpha3"
-#if [ "$1" == "--version" ] || [ "$1" == "-v" ]; then
-#	echo -e "\n$version\n"
-#	exit 0
-#fi
+version="0.6.3-alpha3"
+if [ "$1" == "--version" ] || [ "$1" == "-v" ]; then
+	echo -e "\n$version\n"
+	exit 0
+fi
 cache="/etc/mrai"
 gitautocache="/etc/mrai/gitauto"
 gitmancache="/etc/mrai/gitman"
@@ -460,7 +460,7 @@ gitupdate () {
 	fi
 	cd "$cache"
 	#do this for each app installed from GitHub
-	for each in "$pass"; do
+	for each in $pass; do
 		pass1="$each"
 		if $( ls | grep -q '$z'); then
 			cd "$pass1"
@@ -600,20 +600,20 @@ To Search:
    mrai -S {package-name}
 
 Options:
--c, --clean		Delete old *.deb files, old config files, and old Github files
+-c		Delete old *.deb files, old config files, and old Github files
 
--i, --install		Install an app, if none of the below options are given, check in the following order:
+-i		Install an app, if none of the below options are given, check in the following order:
 				Github automatic,
 				apt-get,
 				snap,
 				flatpak,
 				Github manual
 
-	-a, --apt	Install just from apt-get. In which case, usage will be:
+	-a	Install just from apt-get. In which case, usage will be:
 
 				mrai -i -a {apt-package-name}
 
-	-g, --git	Install just from Github, In which case, usage will be:
+	-g	Install just from Github, In which case, usage will be:
 			
 				mrai -i -g {/github-username/github-repo-name (or Github URL)}
 				
@@ -621,27 +621,27 @@ Options:
 			automaticlly. Please only use the automatic method if the Repo uses a Makefile to install it's software on your
 			system.
 
-	-s, --snap 	Install just from snapd, In which case, usage will be:
+	-s	Install just from snapd, In which case, usage will be:
 
 				mrai -i -s {snap-name}
 	
-	-f, --flat	Install as Flatpak, In which case, usage will be:
+	-f	Install as Flatpak, In which case, usage will be:
 
 				mrai -i -f {flatpak-name}
 
--h, --help		Display this help dialoge and exit.
+-h		Display this help dialoge and exit.
 
--r, --remove,		Uninstall an app. {name-installed-under} refers to the name given to refer to the GitHub installation,
-  --uninstall			the name of the apt package, the name of the snap, or the name of the flatpak, depending on how it was installed
+-r		Uninstall an app. {name-installed-under} refers to the name given to refer to the GitHub installation,
+			the name of the apt package, the name of the snap, or the name of the flatpak, depending on how it was installed
 
--S, --search,		Search for an app. For GitHub based apps, this only works if they are installed. To find apps to install from GitHub,
-  --find			please vist https://www.github.com
+-S		Search for an app. For GitHub based apps, this only works if they are installed. To find apps to install from GitHub,
+			please vist https://www.github.com
 	
-	-a, --apt	Search for an app through apt-get
+	-a	Search for an app through apt-get
 
-	-s, --snap	Search for an app through snap
+	-s	Search for an app through snap
 
-	-f, --flat	Search for an app through flatpak
+	-f	Search for an app through flatpak
 
 	--ga		Search for an app that was installed using GitHub Automatic Method
 
@@ -649,151 +649,168 @@ Options:
 
 	--git		Search for an app installed from GitHub, regardless of method
 
--u, --update		Update your software. This may or may not work for packages installed from Github.
+-u		Update your software. This may or may not work for packages installed from Github.
 
-	-a, --apt	Update from only apt-get
+	-a	Update from only apt-get
 
-	-f, --flat	Update from only Flatpak
+	-f	Update from only Flatpak
 
-	-g, --git	Update from only Github
+	-g	Update from only Github
 	
-	-s, --snap	Update only installed snaps"
-x="$1"
+	-s	Update only installed snaps"
 y="$2"
 z="$3"
 w="$4"
 #Great! Variables done. Lets make some code that will run EVERY TIME
 #check if $x is set. if it isn't, print the help dialoge and exit
-#
-#The below commented out lines are development code for a change later in mrai.
-#If uncommented they will most likely break mrai as is.
-#u=""
-#S=""
-#i=""
-#r=""
-#c=""
-#while getopts 'uSirhc' flag; do
-#	case "${flag}"; do
-#		u) 
-#			while getopts 'asfg' flag2; do
-#				case "${flag2}"; do
-#					a) u="$u a" ;;
-#					s) u="$u s" ;;
-#					f) u="$u f" ;;
-#					g) u="$u g" ;;
-#					*) 
-#						if [ "$1" == "-u" ]; then
-#							u="a s f g"
-#						else
-#							echo -e "\nSorry. This option is not recognized.\n"
-#							exit 1
-#						fi
-#						;;
-#				esac
-#			done
-#			;;
-#		S) 
-#			while getopts 'asfg' flag2; do
-#				case "${flag2}"; do
-#					a) S="$S a" ;;
-#					s) S="$S s" ;;
-#					f) S="$S f" ;;
-#					g) 
-#						while getopts 'ma' flag3; do
-#							case "${flag2}"; do
-#								m) S="$S m" ;;
-#								a) S="$S o" ;;
-#								*) S="$S l" ;;
-#							esac
-#						done
-#						;;
-#					*) 
-#						if [ "$1" == "-S" ]; then
-#							S="a s f g"
-#						else
-#							echo -e "\nSorry. This option is not recognized.\n"
-#							exit 1
-#						fi
-#						;;
-#				esac
-#			done
-#			;;
-#		i) 
-#			while getopts 'asfg' flag2; do
-#				case "${flag2}"; do
-#					a) i="a" ;;
-#					s) i="s" ;;
-#					f) i="f" ;;
-#					g) 
-#						while getopts 'ma' flag3; do
-#							case "${flag3}"; do
-#								m) i="gm" ;;
-#								a) i="ga" ;;
-#								*) echo -e "\nError in main function. Please file a bug report at https://github.com/Batcastle/mrai/issues\n"; exit 2 ;;
-#							esac
-#						done
-#						;;
-#					*) 
-#						if [ "$1" == "-i" ]; then
-#							i="all"
-#						else
-#							echo -e "\nSorry. This option is not recognized.\n"
-#							exit 1
-#						fi
-#						;;
-#				esac
-#			done
-#			;;
-#		r) r=1 ;;
-#		c) c=1 ;;
-#		h) echo -e "\n$h\n"; exit 0 ;;
-#		*) Error out
-#	esac
-#done
-#this will be changed to an error checker for the case above
-if [ -z "$x" ]; then
-	echo -e "\n$h\n"
-	exit 1
+#new flag detection system
+#set variables so that they can iterated over without throwing errors
+u=""
+S=""
+i=""
+r=""
+c=""
+#get flags
+while getopts 'uSirhc' flag; do
+	case "${flag}" in
+		#update flag
+		u) 
+			if [ "$1" == "-u" ]; then
+				u="a s f g"
+				break
+			fi
+			while getopts 'asfg' flag; do
+				case "${flag}" in
+					a) u="$u a" ;;
+					s) u="$u s" ;;
+					f) u="$u f" ;;
+					g) u="$u g" ;;
+					*) 
+						if [ "$1" == "-u" ]; then
+							u="a s f g"
+						else
+							echo -e "\nSorry. This option is not recognized.\n"
+							exit 1
+						fi
+						;;
+				esac
+			done
+			;;
+		#search flag
+		S) 
+			if [ "$1" == "-S" ]; then
+				S="a"
+				break
+			fi			
+			while getopts 'asfg' flag; do
+				case "${flag}" in
+					a) S="$S p" ;;
+					s) S="$S s" ;;
+					f) S="$S f" ;;
+					g) 
+						if [ "$1" == "-Sg" ]; then
+							S="$S l"
+							break
+						fi
+						while getopts 'ma' flag; do
+							case "${flag}" in
+								m) S="$S m" ;;
+								a) S="$S o" ;;
+								*) S="$S l" ;;
+							esac
+						done
+						;;
+					*) 
+						if [ "$1" == "-S" ]; then
+							S="a"
+						else
+							echo -e "\nSorry. This option is not recognized.\n"
+							exit 1
+						fi
+						;;
+				esac
+			done
+			;;
+		#install flag
+		i) 
+			if [ "$1" == "-i" ]; then
+				i="l"
+				break
+			fi
+			while getopts 'asfg' flag; do
+				case "${flag}" in
+					a) i="a" ;;
+					s) i="s" ;;
+					f) i="f" ;;
+					g) 
+						while getopts 'ma' flag; do
+							case "${flag}" in
+								m) i="gm" ;;
+								a) i="ga" ;;
+								*) echo -e "\nError in main function. Please file a bug report at https://github.com/Batcastle/mrai/issues\n"; exit 2 ;;
+							esac
+						done
+						;;
+					*) 
+						if [ "$1" == "-i" ]; then
+							i="l"
+						else
+							echo -e "\nSorry. This option is not recognized.\n"
+							exit 1
+						fi
+						;;
+				esac
+			done
+			;;
+		#remove flag
+		r) r=1 ;;
+		#clean flag
+		c) c=1 ;;
+		#help flag
+		h) echo -e "\n$h\n"; exit 0 ;;
+		#all else
+		*) Error out
+	esac
+done
+#check to make sure SOMETHING is set
+if [ -z "$i" ] && [ -z "$r" ] && [ -z "$c" ] && [ -z "$S" ] && [ -z "$u" ]; then
+	echo -e "\nError in main function: Case failed with 0 commands reported. Please file a bug report at https://github.com/Batcastle/mrai/issues\n"
+	exit 2
 else
 	#check for the install flags
-	#if [[ ! -z "$i" ]]; then
-	if [ "$x" == "-i" ] || [ "$x" == "--install" ]; then
+	if [[ ! -z "$i" ]]; then
+		echo "$i"
 		#check for apt sub-flag
-		#if [ "$i" == "a" ]; then
-		if [ "$y" == "-a" ] || [ "$y" == "--apt" ]; then
+		if [ "$i" == "a" ]; then
 			#set $pass to $z that way aptinstall can use it
-			pass="$z"
+			pass="$y"
 			( aptinstall && exit 0 ) || exit 2
 		#git sub-flag
-		elif [ "$y" == "-g" ] || [ "$y" == "--git" ]; then
+		elif $(echo "$i" | grep -q "g"); then
 			#manual sub-flag
-			#if [ "$i" == "gm" ]; then
-			if [ "$z" == "-m" ] || [ "$z" == "--manual" ]; then
-				pass="$w"
+			if [ "$i" == "gm" ]; then
+				pass="$y"
 				( gitmaninstall && exit 0 ) || exit 2
 			#auto sub-flag
-			#if [ "$i" == "ga" ]; then
-			elif [ "$z" == "-a" ] || [ "$z" == "--auto" ]; then
-				pass="$w"
+			elif [ "$i" == "ga" ]; then
+				pass="$y"
 				( gitautoinst && exit 0 ) || exit 2
 			else
-				pass="$z"
+				pass="$y"
 				( gitautoinst && exit 0 ) || ( gitmaninstall && exit 1 ) || exit 2
 			fi
 		#snap sub-flag
-		#if [ "$i" == "s" ]; then
-		elif [ "$y" == "-s" ] || [ "$y" == "--snap" ]; then
-			pass="$z"
+		elif [ "$i" == "s" ]; then
+			pass="$y"
 			( snapinstall && exit 0 ) || exit 2
 		#flatpak sub-flag
-		#if [ "$i" == "f" ]; then
-		elif [ "$y" == "-f" ] || [ "$y" == "--flat" ]; then
-			pass="$z"
+		elif [ "$i" == "f" ]; then
+			pass="$y"
 			( flatinstall && exit 0 ) || exit 2
 		#none of the sub-flags where passed, so try ALL install methods until one works
-		else
+		elif [ "$i" == "l" ]; then
 			echo -e "\nAttempting to install\n"
-			pass="$y"	
+			pass="$z"	
 			{
 				aptinstall
 			} || {
@@ -801,7 +818,7 @@ else
 			} || {
 				flatinstall
 			} || {
-				pass=$z
+				pass="$y"
 				gitautoinst
 			} || {
 				gitmaninstall
@@ -809,10 +826,12 @@ else
 				echo -e "\nWe're sorry. All installation methods failed.\nPlease make sure that you have the Github username,\nrepo name, and package name spelled correctly\n"
 				exit 2
 			}
+		else
+			echo -e "\nAn error has occured in main function. Please file a bug report at https://github.com/Batcastle/mrai/issues\n"
+			exit 2
 		fi
 	#remove / uninstall flag
-	#elif [[ ! -z "$r" ]] && [ "$r" == "1" ]; then
-	elif [ "$x" == "-r" ] || [ "$x" == "--remove" ] || [ "$x" == "--uninstall" ]; then
+	elif [[ ! -z "$r" ]] && [ "$r" == "1" ]; then
 		#check the way a certain app is installed so it can be properly removed
 		pass="$y"		
 		checkinstalltype
@@ -833,111 +852,77 @@ else
 			exit 1
 		else
 			#if we get something other than a value from 1 and 5 set to $type, we have a SERIOUS issue. Please submit a bug report in this instance
-			echo -e "\nmrai has encountered an error in function {checkinstalltype}.\nPlease contact Thomas Castleman at draugeros@gmail.com to submit a bug report.\n"
+			echo -e "\nmrai has encountered an error in function {checkinstalltype}.\nPlease submit a bug report at https://github.com/Batcastle/mrai/issues.\n"
 			exit 2
 		fi
 	#update flag
-#	elif [[ ! -z "$u" ]]; then
-#		for x in "$u"; do
-#			if [ "$x" == "f" ]; then
-#				flatupdate
-#			elif [ "$x" == "g" ]; then
-#				if [[ ! -z "$2" ]]; then 
-#					pass="$2"
-#				else
-#					t=$(gitautolist)
-#					r=$(gitmanlist)
-#					pass="$t $r"
-#				fi
-#				gitupdate
-#			elif [[ "$x" == "a" ]]; then
-#				if $(echo "$u" | grep -q "s"); then
-#					pkexec aptupdate -s
-#				else
-#					pkexec aptupdate
-#				fi
-#			elif [[ "$x" == "s" ]]; then
-#				if $(echo "$u" | grep -q "a"); then
-#					continue
-#				else
-#					snapupdate
-#				fi
-#			else
-#				continue
-#			fi
-#		done
-	elif [ "$x" == "-u" ] || [ "$x" == "--update" ]; then
-		#apt sub-flag
-		if [ "$y" == "-a" ] || [ "$y" == "--apt" ]; then
-			pkexec aptupdate
-		#flatpak sub-flag
-		elif [ "$y" == "-f" ] || [ "$y" == "--flat" ]; then
-			flatupdate
-		#github sub-flag
-		elif [ "$y" == "-g" ] || [ "$y" == "--git" ]; then
-			#if $z is set, just update that app
-			if [[ ! -z $z ]]; then
-				pass="$z"
-			#otherwise, update them all
+	elif [[ ! -z "$u" ]]; then
+		for x in $u; do
+			if [ "$x" == "f" ]; then
+				flatupdate
+			elif [ "$x" == "g" ]; then
+				if [[ ! -z "$2" ]]; then 
+					pass="$2"
+				else
+					t=$(gitautolist)
+					r=$(gitmanlist)
+					pass="$t $r"
+				fi
+				gitupdate
+			elif [[ "$x" == "a" ]]; then
+				if $(echo "$u" | grep -q "s"); then
+					pkexec aptupdate -s
+				else
+					pkexec aptupdate
+				fi
+			elif [[ "$x" == "s" ]]; then
+				if $(echo "$u" | grep -q "a"); then
+					continue
+				else
+					snapupdate
+				fi
 			else
-				t=$(gitautolist)
-				r=$(gitmanlist)
-				pass="$t $r"
+				continue
 			fi
-			gitupdate
-		#Force update snaps, snap sub-flag
-		elif [ "$y" == "-s" ] || [ "$y" == "--snap" ]; then
-			snapupdate
-		else
-			#update all isntalled apps
-			#snapupdate does not need to be called. Just pass a -s flag to aptupdate and it will run it itself
-			#that way the user's password only has to be asked once
-			pkexec aptupdate -s
-			flatupdate
-			t=$(gitautolist)
-			r=$(gitmanlist)
-			pass="$t $r"
-			gitupdate
-		fi
-	#help flag
-	#this will be removed when the update gets applied
-	elif [ "$x" == "-h" ] || [ "$x" == "--help" ]; then
-		echo -e "\n$h\n"
-		exit 0
+		done
 	#search flag
-#	elif [[ ! -z "$S" ]]; then
-	elif [ "$x" == "-S" ] || [ "$x" == "--search" ] || [ "$x" == "--find" ]; then
+	elif [[ ! -z "$S" ]]; then
 		#apt sub-flag, only search from apt
-#		if $(echo "$S" | grep -q "a"); then
-		if [ "$y" == "-a" ] || [ "$y" == "--apt" ]; then
-			apt search "$z"
+		if $(echo "$S" | grep -q "p"); then
+			apt search "$y"
 		#flatpak sub-flag, only search from flatpak
-#		if $(echo "$S" | grep -q "f"); then
-		elif [ "$y" == "-f" ] || [ "$y" == "--flat" ]; then
-			flatpak search "$z"
+		elif $(echo "$S" | grep -q "f"); then
+			if [ -f "$cache"/flatpak.flag ]; then
+				flatpak search "$y"
+			else
+				echo -e "\nFlatpak is not installed. Please run \"mrai -ia flatpak\" to install it.\n"
+			fi
 		#snap sub-flag, only search from snap
-#		if $(echo "$S" | grep -q "s"); then
-		elif [ "$y" == "-s" ] || [ "$y" == "--snap" ]; then
-			snap search "$z"
+		elif $(echo "$S" | grep -q "s"); then
+			snap search "$y"
 		#Manual GitHub sub-flag, only search apps installed using manual method from GitHub
-#		if $(echo "$S" | grep -q "m"); then
-		elif [ "$y" == "--gm" ]; then
-			list=$(gitmanlist | grep "$z")
-			echo -e "\n$list\n"
+		elif $(echo "$S" | grep -q "m"); then
+			list=$(gitmanlist | grep "$y")
+			echo -e "\nInstalled through Manual Method:\n$list\n"
 		#Automatic GitHub sub-flag, only search apps installed using automatic method from GitHub
-#		if $(echo "$S" | grep -q "o"); then
-		elif [ "$y" == "--ga" ]; then
-			list=$(gitautolist | grep "$z")
-			echo -e "\n$list\n"
+		elif $(echo "$S" | grep -q "o"); then
+			list=$(gitautolist | grep "$y")
+			echo -e "\nInstalled through Automatic Method:\n$list\n"
 		#generel GitHub sub-flag, only search apps installed from GitHub, regardless of method
-#		if $(echo "$S" | grep -q "l"); then
-		elif [ "$y" == "--git" ]; then
-			list1=$(gitmanlist | grep "$z")
-			list2=$(gitautolist | grep "$z")
-			list="$list1 $list2"
+		elif $(echo "$S" | grep -q "l"); then
+			list1=$(gitmanlist | grep "$y")
+			list2=$(gitautolist | grep "$y")
+			list="Installed through Manual Method:
+$list1
+
+Installed through Automatic Method:
+
+$list2
+
+"
 			echo -e "\n$list\n"
 		#search EVERYTHING
-		else
+		elif [ "$S" == "a" ]; then
 			list1=$(gitmanlist | grep "$y")
 			list2=$(gitautolist | grep "$y")
 			echo -e "\nApt packages:\n"
@@ -966,11 +951,7 @@ $list2
 			fi
 		fi
 	#version flag
-	#this will be moved
-	elif [ "$1" == "--version" ]; then
-		echo -e "\n$version\n"
-#	elif [[ ! -z "$c" ]]; then
-	elif [ "$x" == "-c" ] || [ "$x" == "--clean" ]; then
+	elif [[ ! -z "$c" ]]; then
 		clean
 	#no recognized flags passed
 	else
