Update mrai
More commenting (ugh)

diff --git a/mrai b/mrai
--- a/mrai
+++ b/mrai
@@ -20,7 +20,7 @@
 #  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 #  MA 02110-1301, USA.
 #
-version="0.4.7-alpha2"
+version="0.4.8-alpha2"
 #Start Defining Functions
 
 #Force update snaps
@@ -408,13 +408,16 @@ gitremove () {
 				else
 					echo -e "\nAll other options on the install script have failed. Please look online for documentation on how to remove this app.\nWe are sorry for any inconvenience.\n" && exit 2
 				fi
+				#Sleep so the user can read what we just echoed out
 				sleep 3s
+				#run the file with the designated option as root
 				(( pkexec $(pwd)/"$run" "$opt" ) && ( sent=1 )) || ( ((num+=1)) )
 			done
 		elif [ "$root" == "RUN_AS_ROOT=no" ] || [ "$root" == "RUN_AS_ROOT=null" ]; then
 			echo -e "\nAttempting to uninstall. Please wait . . .\n"
 			sent=0
 			num=1
+			#try different commands to the file indicated in the *.flag file
 			while [ "$sent" == "0" ]; do
 				echo -e "\nTry $num . . .\n"
 				if [ "$num" == "1" ]; then
@@ -428,10 +431,16 @@ gitremove () {
 				else
 					echo -e "\nAll other options on the install script have failed. Please look online for documentation on how to remove this app.\nWe are sorry for any inconvenience.\n" && exit 2
 				fi
+				#Sleep so the user can read what we just echoed out
 				sleep 3s
+				#run the file with the designated option, BUT NOT AS ROOT
 				(( exec $(pwd)/"$run" "$opt" ) && ( sent=1 )) || ( ((num+=1)) )
 			done
 		else
+			#Okay, if we get down here, something fucked up.
+			#The contents of ANY *.flag file made by one of the two git install functions (see gitmaninstall and gitautoinst)
+			#should contain both an "ADDRESS" field and a "RUN_AS_ROOT" feild. RUN_AS_ROOT can only be a "yes", "no", or "null"
+			#if RUN_AS_ROOT is set to anything else, this will be displayed
 			echo -e "\nWe're sorry. The function gitremove in /bin/mrai has encountered an error. Please contact the devs for help.\n" && exit 2
 		fi
 	else
@@ -441,24 +450,33 @@ gitremove () {
 			
 }
 
+#remove flatpak packages
 flatremove () {
+	#flatpak doesn't need root, so not called as such
 	flatpak remove "$pass"
 }
 
+#remove snap packages
 snapremove () {
+	#snap elevates itself to root, so not gonna bother calling it as root. That way, more of it runs without root access,
+	#allowing it to be more secure, while also saving space in this file
 	snap remove "$pass"
 }
 
+#update apps installed through GitHub
 gitupdate () {
+	#check first to see if gitupdate got passed an empty or null string. Cause why bother if nothing to use?
 	if [ "$pass" == " " ] || [ "$pass" == "" ]; then
 		echo -e "\nNo Apps installed from GitHub through mrai.\n"
 		return 0
 	fi
 	cd "$cache"
+	#do this for each app installed from GitHub
 	for each in "$pass"; do
 		pass1="$each"
 		if $( ls | grep -q '$z'); then
 			cd "$pass1"
+			#read the *.flag file and parse it for info
 			flag=$(ls | grep ".flag")
 			root=$(cat $flag | grep "RUN_AS_ROOT=")
 			add=$(cat $flag | grep "ADDRESS=")
@@ -468,6 +486,7 @@ gitupdate () {
 			back=$(pwd)
 			del=$(find -type f -name "*.deb")
 			cd $HOME/.mrai/"$pass1"
+			#"Call home" and get the new software
 			if $(echo "$call" | grep -q 'https://github.com/') || $(echo "$call" | grep -q 'http://github.com/'); then
 				git clone "$call"
 			elif $(echo "$call" | grep -q 'github.com/'); then
@@ -475,13 +494,18 @@ gitupdate () {
 			else
 				git clone https://github.com/$call
 			fi
+			#check if $run is set, if it isn't, we are using the Makefile method of doing things
 			if [[ -z $run ]]; then
-				make update || make && make install || echo -e "\nMakefile update method failed.\n"
+				#some Makefiles have an update function. Others you have to reinstall
+				( make update ) || ( make && make install ) || echo -e "\nMakefile update method failed.\n"
+				#clean up
 				rm "$back"/"$del"
 				deb=$(find -type f -name "*.deb")
 				cp "$deb" "$gitautocache"/"$pass1"
 			else
+				#check if we need to run this as root
 				if [ "$root" == "RUN_AS_ROOT=yes" ]; then
+					#run the file as root
 					pkexec $(pwd)/$run $opt
 					pkexec checkinstall
 					rm "$back"/"$del"
